const date = new Date();

export const post = [
    {
        parent_category: null,
        category: 'music',
        title: 'Eminem – Stronger Than I Was',
        author: 'krishna',
        status: 'published',
        views: 54,
        url: 'eminem-stronger-than-i-was',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '1',
        content: null,
        content_type: 'music',
        order: 1,
        template: 1
    },
    {
        parent_category: null,
        category: 'music',
        title: 'Dj Dark – Chill Vibes',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'dj-dark-chill-vibes',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '2',
        content: null,
        content_type: 'music',
        order: 2,
        template: 1
    },
    {
        parent_category: null,
        category: 'music',
        title: 'Leona Lewis – Bleeding Love (Dj Dark & Adrian Funk Remix)',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'leona-lewis-bleeding-love-dj-dark-adrian-funk-remix',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '3',
        content: null,
        content_type: 'music',
        order: 3,
        template: 1
    },
    {
        parent_category: 'design',
        category: 'architecture',
        title: 'Silicon Valley Guru Affected by the Fulminant Slashed Investments',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'silicon-valley-guru-affected-by-the-fulminant-slashed-investments',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '4',
        content: null,
        content_type: 'common',
        order: 4,
        template: 1
    },
    {
        parent_category: 'design',
        category: 'architecture',
        title: 'Watch Awesome Kate Go Full Cooking Pro in England this Week',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'watch-awesome-kate-manner-go-full-cooking-pro-in-england-this-week',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '5',
        content: null,
        content_type: 'common',
        order: 5,
        template: 1
    },
    {
        parent_category: 'design',
        category: 'architecture',
        title: 'The Next Wave of Superheroes Has Arrived with Astonishing Impact',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'the-next-wave-of-superheroes-has-arrived-with-astonishing-impact',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '6',
        content: null,
        content_type: 'common',
        order: 6,
        template: 1
    },
    {
        parent_category: 'design',
        category: 'architecture',
        title: 'The Weirdest Places Ashes Have Been Scattered in South America',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'the-weirdest-places-ashes-have-been-scattered-in-south-america',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '7',
        content: null,
        content_type: 'common',
        order: 7,
        template: 1
    },
    {
        parent_category: 'design',
        category: 'architecture',
        title: 'How Nancy Reagan Gave Glamour and Class to the White House',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'how-nancy-reagan-gave-glamour-and-class-to-the-white-house',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '8',
        content: null,
        content_type: 'common',
        order: 8,
        template: 1
    },
    {
        parent_category: 'design',
        category: 'architecture',
        title: 'Mobile Marketing is Said to Be the Future of E-Commerce',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'mobile-marketing-is-said-to-be-the-future-of-e-commerce',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '9',
        content: null,
        content_type: 'common',
        order: 9,
        template: 1
    },
    {
        parent_category: 'design',
        category: 'architecture',
        title: 'Entrepreneurial Advertising: The Future Of Marketing',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'entrepreneurial-advertising-the-future-of-marketing',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '10',
        content: null,
        content_type: 'common',
        order: 10,
        template: 1
    },
    {
        parent_category: 'design',
        category: 'architecture',
        title: 'Social Media Marketing for Franchises is Meant for Women',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'social-media-marketing-for-franchises-is-meant-for-women',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '11',
        content: null,
        content_type: 'common',
        order: 11,
        template: 1
    },
    {
        parent_category: 'design',
        category: 'architecture',
        title: 'Radio Air Time Marketing: A New Strategy for the Economy',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'customer-engagement-marketing-a-new-strategy-for-the-economy',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '12',
        content: null,
        content_type: 'common',
        order: 12,
        template: 1
    },
    {
        parent_category: 'design',
        category: 'architecture',
        title: 'Now Is the Time to Think About Your Small-Business Success',
        author: 'krishna',
        status: 'published',
        views: 52,
        url: 'now-is-the-time-to-think-about-your-small-business-success',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '13',
        content: null,
        content_type: 'common',
        order: 13,
        template: 1
    },
    {
        parent_category: null,
        category: 'fashion',
        title: 'WordPress News Magazine Charts the Most Chic and Fashionable Women of New York City',
        author: 'krishna',
        status: 'published',
        views: 54,
        url: 'wordpress-news-magazine-charts-the-most-chic-and-fashionable-women-of-new-york-city',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '14',
        content: null,
        content_type: 'common',
        order: 14,
        template: 1
    },
    {
        parent_category: null,
        category: 'fashion',
        title: 'Expert Advice: The Best Retro Chic Fashion for All Ages',
        author: 'krishna',
        status: 'published',
        views: 18,
        url: 'expert-advice-the-best-retro-chic-fashion-for-all-ages',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '15',
        content: null,
        content_type: 'common',
        order: 15,
        template: 1
    },
    {
        parent_category: null,
        category: 'fashion',
        title: 'Shop The Best Street Style From Paris Fashion Week Shows',
        author: 'krishna',
        status: 'published',
        views: 15,
        url: 'shop-the-best-street-style-from-paris-fashion-week-showsy',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '16',
        content: null,
        content_type: 'common',
        order: 16,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'street-fashion',
        title: 'Summer Fashion Trends 2020: The Pieces That Deserve Attention',
        author: 'krishna',
        status: 'published',
        views: 35,
        url: 'summer-fashion-trends-2020-the-pieces-that-deserve-attention',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '17',
        content: null,
        content_type: 'common',
        order: 17,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'street-fashion',
        title: 'Shanghai Fashion Week Highlights: The Shape of Things to Come',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'shanghai-fashion-week-highlights-the-shape-of-things-to-come',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '18',
        content: null,
        content_type: 'common',
        order: 18,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'street-fashion',
        title: 'Front Row: Marion Hume on Australian Fashion Week Magazine Cover',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'front-row-marion-hume-on-australian-fashion-week-magazine-cover',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '19',
        content: null,
        content_type: 'common',
        order: 19,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'street-fashion',
        title: 'Why Don’t the Top Fashion Designers Wear Their Own Clothes?',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'why-dont-the-top-fashion-designers-wear-their-own-clothes',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '20',
        content: null,
        content_type: 'common',
        order: 20,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'street-fashion',
        title: 'Spring Fashion Show at the University of Michigan Has Started',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'spring-fashion-show-at-the-university-of-michigan-has-started',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '21',
        content: null,
        content_type: 'common',
        order: 21,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'new-look',
        title: 'If You Only Knew How Much Your Outfit Choices Actually Matter',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'if-you-only-knew-how-much-your-outfit-choices-actually-matter',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '22',
        content: null,
        content_type: 'common',
        order: 22,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'new-look',
        title: 'Teens from Local School Amaze as Runway Models at DisArt Show',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'from-local-school-amaze-as-runway-models-at-disart-show',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '23',
        content: null,
        content_type: 'common',
        order: 23,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'new-look',
        title: 'Top Fashion Trends to Look for in Every Important Collection',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'top-fashion-trends-to-look-for-in-every-important-collection',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '24',
        content: null,
        content_type: 'common',
        order: 24,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'new-look',
        title: 'Designer Fashion Show Kicks off with Great Success at Variety',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'designer-fashion-show-kicks-off-with-great-success-at-variety',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '25',
        content: null,
        content_type: 'common',
        order: 25,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'new-look',
        title: 'Olivia Wilde Looking Forward to New Patterned Dress Collection',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'olivia-wilde-looking-forward-to-new-patterned-dress-collection',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '26',
        content: null,
        content_type: 'common',
        order: 26,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'style-hunter',
        title: 'Proenza Schouler Advice to Young Designers: Start Your Own Business',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'proenza-schouler-advice-to-young-designers-start-your-own-business',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '27',
        content: null,
        content_type: 'common',
        order: 27,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'style-hunter',
        title: 'Style Magazine Removes Its Rule About Running Woman Only Covers',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'style-magazine-removes-its-rule-about-running-woman-only-covers',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '28',
        content: null,
        content_type: 'common',
        order: 28,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'style-hunter',
        title: 'Kim Selfie Book Available For Pre-Order, Walks Her Last Runway',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'kim-selfie-book-available-for-pre-order-walks-her-last-runway',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '29',
        content: null,
        content_type: 'common',
        order: 29,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'style-hunter',
        title: 'Academy of Country Music Awards Hosts this Year’s Fashion Show',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'academy-of-country-music-awards-hosts-this-years-fashion-show',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '30',
        content: null,
        content_type: 'common',
        order: 30,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'style-hunter',
        title: 'Just in Time for Spring: Community Style Turnaround has Major Impact',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'just-in-time-for-spring-community-style-turnaround-has-major-impact',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '31',
        content: null,
        content_type: 'common',
        order: 31,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'vogue',
        title: 'How to Find the Perfect Sunglasses for Your Hair & Face Shape',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'how-to-find-the-perfect-sunglasses-for-your-hair-face-shape',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '32',
        content: null,
        content_type: 'common',
        order: 32,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'vogue',
        title: 'What to Wear on Gala Night? We Asked the Biggest Names!',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'what-to-wear-on-gala-night-we-asked-the-biggest-names',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '33',
        content: null,
        content_type: 'common',
        order: 33,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'vogue',
        title: '10 Fabulous Over-the-ankle Shoes to Wear This Cold Season',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: '10-fabulous-over-the-ankle-shoes-to-wear-this-cold-season',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '34',
        content: null,
        content_type: 'common',
        order: 34,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'vogue',
        title: 'Style Spy: Fashion Model Goes Casual in Faux Furr and Plaid',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'style-spy-fashion-model-goes-casual-in-faux-furr-and-plaid',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '35',
        content: null,
        content_type: 'common',
        order: 35,
        template: 1
    },
    {
        parent_category: 'fashion',
        category: 'vogue',
        title: 'Fashion Outfit Ideas From the Biggest Instagram Influencers',
        author: 'krishna',
        status: 'published',
        views: 38,
        url: 'fashion-outfit-ideas-from-the-biggest-instagram-influencers',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '36',
        content: null,
        content_type: 'common',
        order: 36,
        template: 1
    },
    {
        parent_category: null,
        category: 'technology',
        title: 'The Top 10 Tech Events that You Don’ Want to Miss this Summer',
        author: 'krishna',
        status: 'published',
        views: 3303,
        url: 'fashion-outfit-ideas-from-the-biggest-instagram-influencers',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '37',
        content: null,
        content_type: 'common',
        order: 37,
        template: 1
    },
    {
        parent_category: null,
        category: 'technology',
        title: 'New Screen Savers: The Show Launched Video into the Stratosphere',
        author: 'krishna',
        status: 'published',
        views: 4581,
        url: 'new-screen-savers-the-show-launched-video-into-the-stratosphere',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '38',
        content: null,
        content_type: 'common',
        order: 38,
        template: 1
    },
    {
        parent_category: null,
        category: 'technology',
        title: 'Amazon’s Apple Watch Killer Will be Free and Sell you Everything',
        author: 'krishna',
        status: 'published',
        views: 6866,
        url: 'amazons-apple-watch-killer-will-be-free-and-sell-you-everything',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '39',
        content: null,
        content_type: 'common',
        order: 39,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'gadgets',
        title: 'Discover a Better Camera for Your YouTube Account',
        author: 'krishna',
        status: 'published',
        views: 10036,
        url: 'discover-a-better-camera-for-your-youtube-account',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '40',
        content: null,
        content_type: 'common',
        order: 40,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'gadgets',
        title: 'Game Changing Virtual Reality Console Hits the Market',
        author: 'krishna',
        status: 'published',
        views: 15545,
        url: 'game-changing-virtual-reality-console-hits-the-market',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '41',
        content: null,
        content_type: 'common',
        order: 41,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'gadgets',
        title: 'Snapdragon Super Chip Mounted on the Latest Photo Cameras',
        author: 'krishna',
        status: 'published',
        views: 5884,
        url: 'snapdragon-super-chip-mounted-on-the-latest-photo-cameras',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '42',
        content: null,
        content_type: 'common',
        order: 42,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'gadgets',
        title: 'New Action Game Refreshed With a Premium Hi-Fi Sound',
        author: 'krishna',
        status: 'published',
        views: 5471,
        url: 'new-action-game-refreshed-with-a-premium-hi-fi-sound',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '43',
        content: null,
        content_type: 'common',
        order: 43,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'gadgets',
        title: 'Sneak Peak: Best Smart Home Gadgets & Features of 2020',
        author: 'krishna',
        status: 'published',
        views: 3984,
        url: 'sneak-peak-best-smart-home-gadgets-features-of-2020',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '44',
        content: null,
        content_type: 'common',
        order: 44,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'mobile-phones',
        title: 'Reasons to Choose the New Generation Water Resistant Phones',
        author: 'krishna',
        status: 'published',
        views: 3204,
        url: 'reasons-to-choose-the-new-generation-water-resistant-phones',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '45',
        content: null,
        content_type: 'common',
        order: 45,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'mobile-phones',
        title: 'China Helps the Smartphone Production Reach Record Levels',
        author: 'krishna',
        status: 'published',
        views: 2809,
        url: 'china-helps-the-smartphone-production-reach-record-levels',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '46',
        content: null,
        content_type: 'common',
        order: 46,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'mobile-phones',
        title: 'The Latest Flagship Smartphone to Come Out of Samsung Factories',
        author: 'krishna',
        status: 'published',
        views: 927,
        url: 'the-latest-flagship-smartphone-to-come-out-of-samsung-factories',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '47',
        content: null,
        content_type: 'common',
        order: 47,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'mobile-phones',
        title: 'iPhone Offers Three Cameras and Brilliand Oled Display for All',
        author: 'krishna',
        status: 'published',
        views: 1058,
        url: 'iphone-offers-three-cameras-and-brilliand-oled-display-for-al',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '48',
        content: null,
        content_type: 'common',
        order: 48,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'mobile-phones',
        title: 'Microsoft Band Review Roundup: What Makes this Phone Stand Out?',
        author: 'krishna',
        status: 'published',
        views: 1195,
        url: 'microsoft-band-review-roundup-what-makes-this-phone-stand-out',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '49',
        content: null,
        content_type: 'common',
        order: 49,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'photography',
        title: 'Discover the Newest Waterproof and Rugged Cameras of 2020',
        author: 'krishna',
        status: 'published',
        views: 1633,
        url: 'discover-the-newest-waterproof-and-rugged-cameras-of-2020',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '50',
        content: null,
        content_type: 'common',
        order: 50,
        template: 1
    },
    {
        parent_category: 'technology',
        category: 'photography',
        title: 'Top Shared Images and Videos in Your Instagram',
        author: 'krishna',
        status: 'published',
        views: 2734,
        url: 'top-shared-images-and-videos-in-your-instagram',
        date: new Date(`August 7, 2022 ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}:`).getTime(),
        img_url: null,
        img_comp: '51',
        content: 'Its own content',
        content_type: 'own',
        order: 51,
        template: 1
    },

]