import Head from 'next/head'
import Highlights from '../components/Highlights';
import FlashNews from '../components/FlashNews';
import { Aside, Main, Section } from '../components/Layout';
import Featured from '../components/Featured';
import StayConnected from '../components/StayConnected';
import { Ad300 } from '../components/Advertisement';
import LatestArticles from '../components/LatestArticles';
import MostPopular from '../components/MostPopular';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Highlights />
      <FlashNews />

      <Section>
        <Main>
          {/* Featured */}
          <Featured />
        </Main>
        <Aside>
          {/* Stay Connected */}
          <StayConnected />
          {/* Advertisement 300 */}
          <Ad300 />
        </Aside>
      </Section>

      <Section>
        <Main>
          {/* Latest Articles */}
          <LatestArticles />
        </Main>
        <Aside>
          {/* Most Popular */}
          <MostPopular />
        </Aside>
      </Section>
    </div>
  )
}

// export async function getServerSideProps(context) {
//   console.log('hii this function is excuting on service side')
//   return {
//     props: {}, // will be passed to the page component as props
//   }
// }