import Head from 'next/head'
import Highlights from '../components/Highlights';
import FlashNews from '../components/FlashNews';
import { Aside, Main, Section } from '../components/Layout';
import Featured from '../components/Featured';
import StayConnected from '../components/StayConnected';
import { Ad300 } from '../components/Advertisement';
import LatestArticles from '../components/pages/Homepage/LatestArticles';
import MostPopular from '../components/MostPopular';
import RecentComments from '../components/RecentComments';
import fetchapi from '../lib/api';
import { wrapper } from '../redux/store';


export default function Home({ recentcomments }) {
  return (
    <>
      <Head>
        <title>Newspaper11 | The Best News Magazine Build on Next Js Framework</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Highlights />
      <FlashNews />

      <Section>
        <Main>
          {/* Featured */}
          <Featured />
        </Main>
        <Aside>
          {/* Stay Connected */}
          <StayConnected />
          {/* Advertisement 300 */}
          <Ad300 />
        </Aside>
      </Section>

      <Section>
        <Main>
          {/* Latest Articles */}
          <LatestArticles />
        </Main>
        <Aside>
          {/* Most Popular */}
          <MostPopular />
          {/* Recent Comments */}
          <div className='mt-7 md:mt-11'>
            <RecentComments recentcomments={recentcomments} />
          </div>
        </Aside>
      </Section>
    </>
  )
}

export const getStaticProps = wrapper.getStaticProps((store) => async (context) => {
// export const getServerSideProps = wrapper.getServerSideProps((store) => async (context) => {
  let recentcomments = await fetchapi(`getcomments?uses=recentcomment&limit=4&page=1`, `${process.env.NEXT_PUBLIC_HOST}`);

  // Dispatch TRENDING
  try {
    const action = { page: 1 };
    const res = await fetchapi(`getarticles?uses=articlesbycategory&category=${'trending'}&type=sub_category&sortby=${'createdAt'}&order=1&limit=${10}&page=${action.page}`, `${process.env.NEXT_PUBLIC_HOST}`);
    store.dispatch({
      type: 'TRENDING',
      payload: {
        articles: res.articles.map(e => ({ ...e, page: action.page })),
        total_articles: res.total_articles,
        page: action.page,
      }
    });
  } catch (error) { console.log(error) }

  // Dispatch FEATURED
  try {
    const action = { page: 1 };
    const res = await fetchapi(`getarticles?uses=articlesbycategory&category=${'featured'}&type=sub_category&sortby=${'views'}&order=-1&limit=${5}&page=${action.page}`, `${process.env.NEXT_PUBLIC_HOST}`);
    store.dispatch({
      type: 'FEATURED',
      payload: {
        articles: res.articles.map(e => ({ ...e, page: action.page })),
        total_articles: res.total_articles,
        page: action.page,
      }
    });
  } catch (error) { console.log(error) };

  // Dispatch ARTICLE_LOCAL
  try {
    const action = { page: 1 };
    const res = await fetchapi(`getarticles?uses=allarticles&limit=${8}&page=${action.page}`, `${process.env.NEXT_PUBLIC_HOST}`)
    store.dispatch({
      type: 'ARTICLES_LOCAL',
      payload: {
        articles: res.articles.map(e => ({ ...e, page: action.page })),
        total_articles: res.total_articles,
        page: action.page
      }
    });
  } catch (error) { console.log(error) }

  // Dispatch MOST_POPULAR
  try {
    const action = { page: 1 };
    const res = await fetchapi(`getarticles?uses=popular&limit=${3}&page=${action.page}`, `${process.env.NEXT_PUBLIC_HOST}`);
    store.dispatch({
      type: 'MOST_POPULAR',
      payload: {
        articles: res.articles.map(e => ({ ...e, page: action.page })),
        total_articles: res.total_articles,
        page: action.page,
      }
    });
  } catch (error) { console.log(error) };

  return {
    props: { recentcomments }, // will be passed to the page component as props
  }
});