import Head from 'next/head'
import Highlights from '../components/Highlights';
import FlashNews from '../components/FlashNews';
import { Aside, Main, Section } from '../components/Layout';
import Featured from '../components/Featured';
import StayConnected from '../components/StayConnected';
import { Ad300 } from '../components/Advertisement';
import LatestArticles from '../components/pages/Homepage/LatestArticles';
import MostPopular from '../components/MostPopular';
import RecentComments from '../components/RecentComments';
import fetchapi from '../lib/api';
import { wrapper } from '../redux/store';
import action from '../redux/action';


export default function Home({ recentcomments }) {
  return (
    <div>
      <Head>
        <title>Newspaper11 | The Best News Magazine Build on Next Js Framework</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Highlights />
      <FlashNews />

      <Section>
        <Main>
          {/* Featured */}
          <Featured />
        </Main>
        <Aside>
          {/* Stay Connected */}
          <StayConnected />
          {/* Advertisement 300 */}
          <Ad300 />
        </Aside>
      </Section>

      <Section>
        <Main>
          {/* Latest Articles */}
          <LatestArticles />
        </Main>
        <Aside>
          {/* Most Popular */}
          <MostPopular />
          {/* Recent Comments */}
          <div className='mt-7 md:mt-11'>
            <RecentComments recentcomments={recentcomments} />
          </div>
        </Aside>
      </Section>
    </div>
  )
}

export const getServerSideProps = wrapper.getServerSideProps((store) => async (context) => {
    let recentcomments = await fetchapi(`getcomments?uses=recentcomment&limit=4&page=1`, `${process.env.NEXT_PUBLIC_HOST}`);
    store.dispatch(action({
      type: 'TRENDING',
      page: 1
    }));
    store.dispatch(action({
      type: 'FEATURED',
      page: 1
    }));
    return {
      props: { recentcomments }, // will be passed to the page component as props
    }
  });